# Generated by Django 3.1.3 on 2020-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object', models.CharField(max_length=60)),
                ('Epoch', models.IntegerField()),
                ('TP', models.FloatField()),
                ('e', models.FloatField()),
                ('I', models.FloatField()),
                ('w', models.FloatField()),
                ('Node', models.FloatField()),
                ('q', models.FloatField()),
                ('Ql', models.FloatField()),
                ('P', models.FloatField()),
                ('MOID', models.FloatField()),
                ('A1', models.FloatField()),
                ('A2', models.FloatField()),
                ('A3', models.FloatField()),
                ('DT', models.FloatField()),
                ('ref', models.CharField(max_length=60)),
                ('Object_name', models.CharField(max_length=60)),
            ],
        ),
    ]
