# Generated by Django 3.1.3 on 2020-11-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_orbitalelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbitalelement',
            name='A1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='orbitalelement',
            name='A2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='orbitalelement',
            name='A3',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='orbitalelement',
            name='DT',
            field=models.FloatField(blank=True),
        ),
    ]
