# Generated by Django 3.1.3 on 2020-11-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201105_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
